In [215]:
import pandas as pd
import pickle

data = pd.read_csv(
    "cdr_files_chosen_columns.csv",
    header=[0, 1],       
    low_memory=False     
)

In [216]:
data.head(5)

,Unnamed: 0_level_0,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
,Unnamed: 0_level_1,INTEGER,INTEGER,INTEGER,INTEGER,VARCHAR(50),INTEGER,INTEGER,VARCHAR(50),VARCHAR(50),...,VARCHAR(129),VARCHAR(129),INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER,INTEGER
0,0,1,16615182,19957562,1704072013,437734693017,16,19957563,4344124999,4344124999,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,1,16615183,19957564,1704078480,436618449646,16,19957565,433738509500050,433738509500050,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,2,1,16615184,19957566,1704085667,436359992566,16,19957567,433738509500050,433738509500050,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,3,1,16615185,19957568,1704087689,9999,16,19957569,4314014190122,4314014190122,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,4,1,16615186,19957570,1704089234,433496903750,0,19957571,4373935601800,4373935601800,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [217]:
data.columns = data.columns.get_level_values(0)

horni uroven pro pojemenovani sloupcu

In [218]:
data = data[[col for col in data.columns if "Unnamed" not in str(col)]]

zbavime se unnamed

In [219]:
data.head(5)

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,1704072013,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,1704078480,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,1704085667,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,1704087689,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,1704089234,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [220]:
len(data.columns)

25

In [221]:
for col in data.columns:
    print(col)

globalCallID_callManagerId
globalCallID_callId
origLegCallIdentifier
dateTimeOrigination
callingPartyNumber
origCause_value
destLegIdentifier
originalCalledPartyNumber
finalCalledPartyNumber
destCause_value
dateTimeConnect
dateTimeDisconnect
lastRedirectDn
pkid
duration
origDeviceName
destDeviceName
origCallTerminationOnBehalfOf
destCallTerminationOnBehalfOf
origCalledPartyRedirectOnBehalfOf
lastRedirectRedirectOnBehalfOf
origCalledPartyRedirectReason
lastRedirectRedirectReason
joinOnBehalfOf
callSecuredStatus

In [222]:
data = data.astype({col: "string" for col in data.select_dtypes(include="object").columns})

In [223]:
for col in ["dateTimeOrigination", "dateTimeConnect", "dateTimeDisconnect"]:
    data[col] = pd.to_numeric(data[col], errors="coerce")
    data[col] = pd.to_datetime(data[col], unit="s")

In [224]:
data.head(5)

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [225]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3805586 entries, 0 to 3805585
Data columns (total 25 columns):
 #   Column                             Dtype
---  ------                             -----
 0   globalCallID_callManagerId         int64
 1   globalCallID_callId                int64
 2   origLegCallIdentifier              int64
 3   dateTimeOrigination                datetime64[ns]
 4   callingPartyNumber                 string
 5   origCause_value                    int64
 6   destLegIdentifier                  int64
 7   originalCalledPartyNumber          string
 8   finalCalledPartyNumber             string
 9   destCause_value                    int64
 10  dateTimeConnect                    datetime64[ns]
 11  dateTimeDisconnect                 datetime64[ns]
 12  lastRedirectDn                     string
 13  pkid                               string
 14  duration                           int64
 15  origDeviceName                     string
 16  destDeviceName                     string
 17  origCallTerminationOnBehalfOf      int64
 18  destCallTerminationOnBehalfOf      int64
 19  origCalledPartyRedirectOnBehalfOf  int64
 20  lastRedirectRedirectOnBehalfOf     int64
 21  origCalledPartyRedirectReason      int64
 22  lastRedirectRedirectReason         int64
 23  joinOnBehalfOf                     int64
 24  callSecuredStatus                  int64
dtypes: datetime64[ns](3), int64(15), string(7)
memory usage: 725.9 MB

nutne prevest do pickel, kvupi datatypum!

In [226]:
data.to_pickle("cdr_clean.pkl")