In [ ]:
#Pokus: normalizace telefonních čísel (Rakousko)
#ZJIŠTĚNÍ délka čísel je různá, někdy s předvolbou, někdy bez, někdy s mezinárodní předvolbou, někdy bez. Někdy jen klapka 
# Maximální délka řetězce je 48 a zřejmě je to kvůli chybě v programu, přepojování a někdy se na 
# řádky ukládají i více čísel zaráz oddělených čárkou, ne vždy jsou oddělena čárkou
import pandas as pd
import pickle

In [7]:
data = pd.read_pickle(r"C:\Users\adamk\Desktop\Digitální akademie DATA\Projekt\skript_02\cdr_files_clean.pkl")

In [8]:
data.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,00437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,00436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,00436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,00433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [9]:
data.dtypes

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                   string[python]
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber            string[python]
finalCalledPartyNumber               string[python]
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                    float64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
dtype: object

In [10]:
phone_columns = ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']
summary_list = []
for column in phone_columns:
    lengths = data[column].astype(str).str.len()
    max_len = lengths.max()
    min_len = lengths.min()

    max_count = (lengths == max_len).sum()
    min_count = (lengths == min_len).sum()

    summary_list.append({'column': column,'column': column,'max_length': max_len,'max_count': max_count,'min_length': min_len,'min_count': min_count})


length_summary = pd.DataFrame(summary_list)
length_summary 
# minální a maximální délka tel, čísla a kolik jich je max_count

                      column  max_length  max_count  min_length  min_count
0         callingPartyNumber          31          1           2        142
1  originalCalledPartyNumber          48          5           1       2458
2     finalCalledPartyNumber          48          6           1       3637

In [11]:
#výpis čísle s max délkou
phone_columns = ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']

records = []

for col in phone_columns:
    col_str = data[col].astype(str)
    lengths = col_str.str.len()
    
    max_len = lengths.max()
    max_numbers = col_str[lengths == max_len]
    
    for num in max_numbers:
        records.append({'column': col, 'max_number': num})

max_numbers_df = pd.DataFrame(records)
max_numbers_df

,column,max_number
0,callingPartyNumber,****1jexsaseedswvjbx13882857044
1,originalCalledPartyNumber,159093173222614841051528007769096515597519394236
2,originalCalledPartyNumber,9793161050955251175111006988544d0837907k2c57s0#0
3,originalCalledPartyNumber,003479672299595294558909634115608275546679232786
4,originalCalledPartyNumber,006191961975667988014144920028192248382697788672
5,originalCalledPartyNumber,28483462447721085369311476056314n702449006126622
6,finalCalledPartyNumber,159093173222614841051528007769096515597519394236
7,finalCalledPartyNumber,9793161050955251175111006988544d0837907k2c57s0#0
8,finalCalledPartyNumber,003479672299595294558909634115608275546679232786
9,finalCalledPartyNumber,006191961975667988014144920028192248382697788672
10,finalCalledPartyNumber,008263275176932020612359902052941803043238226724
11,finalCalledPartyNumber,28483462447721085369311476056314n702449006126622

In [ ]:
# kolik čísel s délkou větší než 15, 16, 17, 18, 19, 20, 25, 30, 35, 40
phone_columns = ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']

long_counts = {}

for col in phone_columns: 
    col_str = data[col].astype(str) 
    lengths = col_str.str.len()

    long_counts[col] = { 
        '>15': (lengths > 15).sum(),
        '>16': (lengths > 16).sum(), 
        '>17': (lengths > 17).sum(),
        '>18': (lengths > 18).sum(), 
        '>19': (lengths > 19).sum(),    
        '>20': (lengths > 20).sum(), 
        '>25': (lengths > 25).sum(), 
        '>30': (lengths > 30).sum(), 
        '>35': (lengths > 35).sum(), 
        '>40': (lengths > 40).sum(), 
    }
pd.DataFrame(long_counts)

     callingPartyNumber  originalCalledPartyNumber  finalCalledPartyNumber
>15              827092                     859128                  790160
>16              645700                     712008                  683411
>17              372199                     379486                  378674
>18                 411                        937                     984
>19                 168                        553                     583
>20                  68                        375                     395
>25                   2                         69                      74
>30                   1                         18                      20
>35                   0                          8                       9
>40                   0                          6                       7

In [ ]:
# příklady čísel s délkou větší než 15, 20, 25, 30, 35, 40
phone_columns = ['callingPartyNumber', 'originalCalledPartyNumber', 'finalCalledPartyNumber']

examples = {}

for col in phone_columns:
    col_str = data[col].astype(str)
    lengths = col_str.str.len()
    
    examples[col] = {
        '>15': col_str[lengths > 15].head(3).tolist(),
        '>20': col_str[lengths > 20].head(3).tolist(),
        '>25': col_str[lengths > 25].head(3).tolist(),
        '>30': col_str[lengths > 30].head(3).tolist(),
        '>35': col_str[lengths > 35].head(3).tolist(),
        '>40': col_str[lengths > 40].head(3).tolist(),
    }

pd.DataFrame(examples)

,callingPartyNumber,originalCalledPartyNumber,finalCalledPartyNumber
>15,"[435474488449626.0, 434658628367051.0, 4346586...","[433738509500150.0, 4356110882901501, 43561108...","[433738509500150.0, 4356110882901501, 43561108..."
>20,"[****2qsqst88981967465, ****1jexsaseedswvjbx13...","[004377360471293290048721, 0043395887742706109...","[004377360471293290048721, 0043395887742706109..."
>25,"[****1jexsaseedswvjbx13882857044, ****9chdxccg...","[004355515131143935400684680, 0043555151311439...","[004355515131143935400684680, 0043555151311439..."
>30,[****1jexsaseedswvjbx13882857044],"[423628304727573996530327323935168042528, 0043...","[423628304727573996530327323935168042528, 0043..."
>35,[],"[423628304727573996530327323935168042528, 1590...","[423628304727573996530327323935168042528, 1590..."
>40,[],[159093173222614841051528007769096515597519394...,[159093173222614841051528007769096515597519394...

In [ ]:
col = 'originalCalledPartyNumber'
value = '159093173222614841051528007769096515597519394236'

# najdeme indexy řádků, kde se hodnota vyskytuje a podívám se v excelu na ně
row_indices = data.index[data[col] == value].tolist()
row_indices # nepodívám se, excel mi otevře jen milion řádků

[1480444]