In [1]:
import pandas as pd

In [2]:
data = pd.read_pickle('cdr_clean_NOb00.pkl')

In [3]:
data.head()

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [5]:
data.shape

(3262838, 25)

Pocet telefonnich cislel koncicich '.0':

In [12]:
end_0 = data['originalCalledPartyNumber'].str.endswith('.0', na=False)
pocet = end_0.sum()
print(f"Počet hodnot origcallednum končících na '.0': {pocet}")

end_0 = data['finalCalledPartyNumber'].str.endswith('.0', na=False)
pocet = end_0.sum()
print(f"Počet hodnot finalcallednum končících na '.0': {pocet}")

end_0 = data['callingPartyNumber'].str.endswith('.0', na=False)
pocet = end_0.sum()
print(f"Počet hodnot callingnum končících na '.0': {pocet}")

Počet hodnot origcallednum končících na '.0': 19670
Počet hodnot finalcallednum končících na '.0': 18143
Počet hodnot callingnum končících na '.0': 13382

Ruzne zapisy volajicich cisel:

In [20]:
start_plus = data['callingPartyNumber'].str.startswith('+', na=False)
pocet = start_plus.sum()
print(f"Počet hodnot callingnum zacinajicich na '+': {pocet}")

start_0 = data['callingPartyNumber'].str.startswith('0', na=False)
pocet = start_0.sum()
print(f"Počet hodnot callingnum zacinajicich na '0': {pocet}")

start_00 = data['callingPartyNumber'].str.startswith('00', na=False)
pocet = start_00.sum()
print(f"Počet hodnot callingnum zacinajicich na '00': {pocet}")

start_000 = data['callingPartyNumber'].str.startswith('000', na=False)
pocet = start_000.sum()
print(f"Počet hodnot callingnum zacinajicich na '000': {pocet}")

Počet hodnot callingnum zacinajicich na '+': 2296913
Počet hodnot callingnum zacinajicich na '0': 2771
Počet hodnot callingnum zacinajicich na '00': 2752
Počet hodnot callingnum zacinajicich na '000': 0

Ruzne zapisy volanych cisel:

In [21]:
start_plus = data['originalCalledPartyNumber'].str.startswith('+', na=False)
pocet = start_plus.sum()
print(f"Počet hodnot origcallednum zacinajicich na '+': {pocet}")

start_0 = data['originalCalledPartyNumber'].str.startswith('0', na=False)
pocet = start_0.sum()
print(f"Počet hodnot origcallednum zacinajicich na '0': {pocet}")

start_00 = data['originalCalledPartyNumber'].str.startswith('00', na=False)
pocet = start_00.sum()
print(f"Počet hodnot origcallednum zacinajicich na '00': {pocet}")

start_000 = data['originalCalledPartyNumber'].str.startswith('000', na=False)
pocet = start_000.sum()
print(f"Počet hodnot origcallednum zacinajicich na '000': {pocet}")

start_0000 = data['originalCalledPartyNumber'].str.startswith('0000', na=False)
pocet = start_0000.sum()
print(f"Počet hodnot origcallednum zacinajicich na '0000': {pocet}")

start_00000 = data['originalCalledPartyNumber'].str.startswith('00000', na=False)
pocet = start_00000.sum()
print(f"Počet hodnot origcallednum zacinajicich na '00000': {pocet}")

Počet hodnot origcallednum zacinajicich na '+': 2062993
Počet hodnot origcallednum zacinajicich na '0': 459907
Počet hodnot origcallednum zacinajicich na '00': 445062
Počet hodnot origcallednum zacinajicich na '000': 110
Počet hodnot origcallednum zacinajicich na '0000': 11
Počet hodnot origcallednum zacinajicich na '00000': 1

Ruzne zapisy konecnych volanych cisel:

In [22]:
start_plus = data['finalCalledPartyNumber'].str.startswith('+', na=False)
pocet = start_plus.sum()
print(f"Počet hodnot finalcallednum zacinajicich na '+': {pocet}")

start_0 = data['finalCalledPartyNumber'].str.startswith('0', na=False)
pocet = start_0.sum()
print(f"Počet hodnot finalcallednum zacinajicich na '0': {pocet}")

start_00 = data['finalCalledPartyNumber'].str.startswith('00', na=False)
pocet = start_00.sum()
print(f"Počet hodnot finalcallednum zacinajicich na '00': {pocet}")

start_000 = data['finalCalledPartyNumber'].str.startswith('000', na=False)
pocet = start_000.sum()
print(f"Počet hodnot finalcallednum zacinajicich na '000': {pocet}")

start_0000 = data['finalCalledPartyNumber'].str.startswith('0000', na=False)
pocet = start_0000.sum()
print(f"Počet hodnot finalcallednum zacinajicich na '0000': {pocet}")

start_00000 = data['finalCalledPartyNumber'].str.startswith('00000', na=False)
pocet = start_00000.sum()
print(f"Počet hodnot finalcallednum zacinajicich na '00000': {pocet}")

Počet hodnot finalcallednum zacinajicich na '+': 1858389
Počet hodnot finalcallednum zacinajicich na '0': 533891
Počet hodnot finalcallednum zacinajicich na '00': 515775
Počet hodnot finalcallednum zacinajicich na '000': 259
Počet hodnot finalcallednum zacinajicich na '0000': 11
Počet hodnot finalcallednum zacinajicich na '00000': 1

Vypsani radku, ktere callednum zacina na 0000 resp. 00000:

In [25]:
start_0000 = data['originalCalledPartyNumber'].str.startswith('0000', na=False)
data[start_0000]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
1503531,2,9406525,39143623,2024-01-16 07:16:11,+43643386910,1,39143624,000000,000000,0,...,SEP001832D63385,<NA>,13,0,0,0,0,0,0,0
2426067,2,10143105,42794775,2024-03-11 08:20:33,+43704834877,1,42794776,0000,0000,0,...,SEP001832D634E8,<NA>,13,0,0,0,0,0,0,0
2510864,2,10210993,43139846,2024-03-14 12:36:54,+4352426265114,1,43139847,00005,00005,0,...,SEP00370DEF5EB9,<NA>,13,0,0,0,0,0,0,0
2576125,2,10263192,43398607,2024-03-19 11:21:29,+43704834411,1,43398608,0000,0000,0,...,SEP001832D6336A,<NA>,13,0,0,0,0,0,0,0
2802021,2,9341375,66526651,2024-01-10 13:24:50,+43456631756,1,66526653,0000,0000,0,...,SEP001832D6300F,<NA>,13,0,0,0,0,0,0,0
2953213,2,9799107,67090341,2024-02-13 10:52:11,+43190933460,1,67090342,0000,0000,0,...,SEPCC6A536F75A9,<NA>,13,0,0,0,0,0,0,0
2981818,2,9887829,50423259,2024-02-20 09:51:14,+43456631756,1,50423260,0000,0000,0,...,SEP001832D6300F,<NA>,13,0,0,0,0,0,0,0
3001177,2,9944555,50497200,2024-02-23 10:03:50,+43456631285,1,50497201,0000,0000,0,...,SEP001832D63089,<NA>,13,0,0,0,0,0,0,0
3089976,2,10199502,50831355,2024-03-14 07:28:15,+43456631871,1,50831358,0000,0000,0,...,SEP001832D63389,<NA>,13,0,0,0,0,0,0,0
3102815,3,2537369,50881654,2024-03-18 09:16:16,+434687759414421,1,50881655,0000,0000,0,...,SEPE8BB34BD1818,<NA>,13,0,0,0,0,0,0,0
3119214,3,2547006,50942331,2024-03-20 14:27:26,+43561125326073,1,50942333,0000,0000,0,...,SEP001832D632D3,<NA>,13,0,0,0,0,0,0,0

Prehled delek volanych cisel:

In [33]:
length = data['originalCalledPartyNumber'].astype(str).str.len()
length_count = length.value_counts().sort_index()
length_count

originalCalledPartyNumber
1       2466
2       1259
3       1083
4     101952
5       3401
6       2749
7      15106
8      15730
9      13786
10     39199
11     76905
12    889332
13    590429
14    478587
15    311697
16    309355
17     37202
18    371946
19       181
20       136
21        61
22        37
23        21
24       141
25        11
26        21
27         4
28        21
29         2
32         7
33         1
34         2
36         1
39         1
45         1
48         5
Name: count, dtype: int64

Prehled delek konecnych volanych cisel:

In [34]:
length = data['finalCalledPartyNumber'].astype(str).str.len()
length_count = length.value_counts().sort_index()
length_count

finalCalledPartyNumber
1       3659
2       2319
3       3551
4      87326
5       3866
6       3200
7     162459
8       5474
9       9044
10     37815
11    112628
12    797612
13    555714
14    515800
15    272149
16    281289
17     36289
18    371956
19       194
20       141
21        62
22        40
23        22
24       145
25        16
26        21
27         4
28        21
29         2
32         7
33         2
34         2
36         1
39         1
45         1
48         6
Name: count, dtype: int64

Delka konecneho volaneho cisla vetsi nez 30:

In [36]:
data[length > 30]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
1363648,2,9294959,38593801,2024-01-08 11:51:43,+437493656393,1,38593810,423628304727573996530327323935168042528,423628304727573996530327323935168042528,0,...,CSFC08K6947,<NA>,13,0,0,0,0,0,0,0
1422553,2,9341466,38822226,2024-01-10 13:26:49,+432213818279617,1,38822227,+4338538092389733m77689906661610,+4338538092389733m77689906661610,0,...,SEP00370DEEB018,<NA>,13,0,0,0,0,0,0,0
1480444,2,9388407,39051720,2024-01-15 08:42:53,+434514700307753,1,39051721,159093173222614841051528007769096515597519394236,159093173222614841051528007769096515597519394236,0,...,CSFC82K184,<NA>,13,0,0,0,0,0,0,0
1771350,2,9620182,40201469,2024-01-31 07:22:42,+437334279620646,1,40201470,+4336368166563084q45076955723658,+4336368166563084q45076955723658,0,...,SEP00370DEEBCE5,<NA>,13,0,0,0,0,0,0,0
1847757,2,9681309,40505998,2024-02-05 08:45:16,+437334279620650,1,40505999,+4336368166563084q45076955723658,+4336368166563084q45076955723658,0,...,SEP00370DED4D69,<NA>,13,0,0,0,0,0,0,0
1847769,2,9681316,40506046,2024-02-05 08:45:23,+437334279620650,1,40506047,+4336368166563084q45076955723658,+4336368166563084q45076955723658,0,...,SEP00370DED4D69,<NA>,13,0,0,0,0,0,0,0
1949574,2,9762783,40911440,2024-02-09 10:28:35,+4373935601805,16,40911441,<NA>,+43476846137711946807110586446352,0,...,CSFC50K6160,<NA>,12,0,0,0,0,0,0,0
2148801,2,9919890,41686426,2024-02-22 07:20:21,+4352599200527313,1,41686427,+43311306407151570i966474545372319,+43311306407151570i966474545372319,0,...,SEP00370DEEBB9B,<NA>,13,0,0,0,0,0,0,0
2461255,2,10171066,42935623,2024-03-12 12:05:24,+4373935601805,1,42935624,102085762877457403570190204754024336,102085762877457403570190204754024336,0,...,CSFC50K6160,<NA>,13,0,0,0,0,0,0,0
2481506,2,10187308,43021422,2024-03-13 10:08:05,+43749919v999,1,43021423,9i2693506039431325076341310777599*,9i2693506039431325076341310777599*,0,...,SEPCC6A536F78E0,<NA>,13,0,0,0,0,0,0,0
2571703,2,10259756,43381697,2024-03-19 09:54:16,+437334279620650,1,43381698,+4336368166563084q45076955723658,+4336368166563084q45076955723658,0,...,SEP00370DED4D69,<NA>,13,0,0,0,0,0,0,0
2591604,2,10275733,43460693,2024-03-20 09:03:33,+432213818279616,1,43460694,+4338538092389733m77689906661610,+4338538092389733m77689906661610,0,...,SEP0036CB4B285A,<NA>,13,0,0,0,0,0,0,0
2663616,2,10333192,43743239,2024-03-25 09:51:47,+432213818279616,1,43743240,+4338538092389733m77689906661610,+4338538092389733m77689906661610,0,...,SEP0036CB4B285A,<NA>,13,0,0,0,0,0,0,0
2910808,1,193698,66931833,2024-02-02 12:33:39,+431785491116,1,66931834,629332544134346230969776669390633,629332544134346230969776669390633,0,...,SEP704509E5FDE8,<NA>,13,0,0,0,0,0,0,0
2917741,3,2427505,66958639,2024-02-05 14:32:31,+43876646253060,1,66958640,9793161050955251175111006988544d0837907k2c57s0#0,9793161050955251175111006988544d0837907k2c57s0#0,0,...,SEP702F53947BF3,<NA>,13,0,0,0,0,0,0,0
3263286,4,5879273,83755793,2024-01-15 10:21:52,+434856169027436,0,83755798,003479672299595294558909634115608275546679232786,003479672299595294558909634115608275546679232786,1,...,CSFC38K917,BK053_040_Tele2,0,12,0,0,0,0,0,0
3271073,4,5885505,83776802,2024-01-16 07:47:43,+439952417598300,0,83776803,006191961975667988014144920028192248382697788672,006191961975667988014144920028192248382697788672,1,...,CSFC38K6118,BK053_015_Tele2,0,12,0,0,0,0,0,0
3353261,4,5951996,67226652,2024-01-25 12:17:53,+43876166591358,16,67226653,<NA>,008263275176932020612359902052941803043238226724,0,...,CSFC38K839,<NA>,12,0,0,0,0,0,0,0
3536834,4,6102383,67748955,2024-02-20 13:25:03,+432404085257221,1,67748958,+43487170320v9372690384j9545249185v6658861060,+43487170320v9372690384j9545249185v6658861060,0,...,CSFC38K6039,<NA>,13,0,0,0,0,0,0,0
3674521,4,6213486,68128687,2024-03-11 11:30:22,+43421139193,1,68128688,28483462447721085369311476056314n702449006126622,28483462447721085369311476056314n702449006126622,0,...,CSFC84K6901,<NA>,13,0,0,0,0,0,0,0

In [37]:
data[length < 4]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
1725,1,16616544,19962598,2024-01-02 07:37:25,+438497505501,1,19962599,5,5,0,...,10.1.52.233,<NA>,13,0,0,0,0,0,0,0
1731,1,16616549,19962617,2024-01-02 07:37:32,+438497505501,1,19962618,15,15,0,...,10.1.52.233,<NA>,13,0,0,0,0,0,0,0
5991,1,16619575,19974084,2024-01-02 08:51:19,+438982467356,1,19974085,51,51,0,...,CUBE_HTEST,<NA>,13,0,0,0,0,0,0,0
5992,1,16619574,19974081,2024-01-02 08:51:19,+438982467356,0,19974082,51,51,1,...,10.112.52.233,CUBE_HTEST,0,12,0,0,0,0,0,0
6006,1,16619588,19974128,2024-01-02 08:51:33,+438982467356,1,19974129,51,51,0,...,CUBE_HTEST,<NA>,13,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3801745,4,6316751,68484410,2024-03-29 09:22:23,+43909432410,1,68484411,41,41,0,...,SEP00335E27EF2E,<NA>,13,0,0,0,0,0,0,0
3802170,4,6317080,68485602,2024-03-29 09:43:44,+43577200560896,16,68485603,<NA>,32,0,...,SEPF88B205ECC70,<NA>,12,0,0,0,0,0,0,0
3802328,4,6317222,68486129,2024-03-29 09:52:30,+437213452506864,16,68486130,<NA>,15,0,...,SEPF88B205EEC43,<NA>,12,0,0,0,0,0,0,0
3802527,4,6317390,68486751,2024-03-29 10:03:06,+43302248115389,1,68486752,51,51,0,...,SEPF88B205EF4F5,<NA>,13,0,0,0,0,0,0,0
3805265,4,6319525,68494084,2024-03-29 14:31:26,+43421139931,1,68494086,000,000,0,...,CSFC84K6749,<NA>,13,0,0,0,0,0,0,0