In [ ]:
import pandas as pd
import pickle
unique_calls = pd.read_pickle("cdr_clean_unique_calls_update_num.pkl")

In [ ]:
columns = unique_calls[['unique_call_id', 'dateTimeConnect', 'dateTimeDisconnect']]
columns.head()

   unique_call_id     dateTimeConnect  dateTimeDisconnect
0          752520 2024-01-01 01:20:14 2024-01-01 01:20:22
1          752521 2024-01-01 03:08:02 2024-01-01 03:08:14
2          752522                 NaT 2024-01-01 05:07:47
3          752523 2024-01-01 05:41:31 2024-01-01 05:42:05
4          752524 2024-01-01 06:07:15 2024-01-01 06:07:50

In [3]:
# pro kazde unique_call_id najit min dateTimeConnect a maxTimeDisconnect
unique_calls = columns.groupby(['unique_call_id']).agg({"dateTimeConnect":"min","dateTimeDisconnect":"max"})

In [4]:
unique_calls['duration_for_unique'] = unique_calls['dateTimeDisconnect'] - unique_calls['dateTimeConnect']

unique_calls.head()

                   dateTimeConnect  dateTimeDisconnect duration_for_unique
unique_call_id
0              2024-01-16 10:11:52 2024-01-16 10:16:23     0 days 00:04:31
1              2024-01-16 10:11:49 2024-01-16 10:12:25     0 days 00:00:36
2              2024-01-16 10:11:50 2024-01-16 10:12:29     0 days 00:00:39
3              2024-01-16 10:11:51 2024-01-16 10:11:51     0 days 00:00:00
4              2024-01-16 10:11:51 2024-01-16 10:17:31     0 days 00:05:40

In [5]:
assert(False)

AssertionError:

In [6]:
# nepocita s NaT, proto count je mensi nez celkovy pocet jedinecnych hovoru
unique_calls.describe()

,dateTimeConnect,dateTimeDisconnect,duration_for_unique
count,2294537,2781787,2294537
mean,2024-02-14 02:22:30.718706432,2024-02-14 03:39:12.398232320,0 days 00:01:47.808982378
min,2024-01-01 00:12:37,2024-01-01 00:13:07,0 days 00:00:00
25%,2024-01-23 08:24:00,2024-01-23 08:33:19,0 days 00:00:00
50%,2024-02-13 15:03:23,2024-02-14 06:55:29,0 days 00:00:29
75%,2024-03-06 15:29:13,2024-03-07 07:20:01,0 days 00:01:51
max,2024-03-31 23:49:49,2024-03-31 23:55:03,0 days 12:00:00
std,NaN,NaN,0 days 00:04:54.130596780

In [8]:
unique_calls.to_pickle('duration_unique_calls.pkl')

In [7]:
unique_calls.shape

(2781787, 3)

In [ ]:
# kolik hovoru je nespojenych
unique_calls.isna().sum()

dateTimeConnect        487250
dateTimeDisconnect          0
duration_for_unique    487250
dtype: int64

In [ ]:
# rozdil mezi celkovym poctem unikatnich hovoru a poctem spojenych hovoru = pocet nespojenych hovoru
2781787 - 2294537

487250

In [ ]:
unique_calls['month'] = unique_calls['dateTimeDisconnect'].dt.to_period('M')

unique_month_calls = (
    unique_calls.groupby('month').size()
)

print(unique_month_calls)

month
2024-01    999724
2024-02    907274
2024-03    874789
Freq: M, dtype: int64

np.int64(2781787)

In [15]:
unique_calls['week'] = unique_calls['dateTimeDisconnect'].dt.to_period('W')

unique_week_calls = (
    unique_calls.groupby('week').size()
)

print(unique_week_calls)
unique_week_calls.sum()

week
2024-01-01/2024-01-07    166294
2024-01-08/2024-01-14    242128
2024-01-15/2024-01-21    231155
2024-01-22/2024-01-28    220858
2024-01-29/2024-02-04    227777
2024-02-05/2024-02-11    217123
2024-02-12/2024-02-18    208005
2024-02-19/2024-02-25    214822
2024-02-26/2024-03-03    218896
2024-03-04/2024-03-10    216431
2024-03-11/2024-03-17    212372
2024-03-18/2024-03-24    212491
2024-03-25/2024-03-31    193435
Freq: W-SUN, dtype: int64

np.int64(2781787)

In [18]:
unique_calls['week'] = unique_calls['dateTimeDisconnect'].dt.to_period('W')

unique_week_calls = (
    unique_calls.groupby('week').agg({'duration_for_unique':'median'}) #,'duration_for_unique':'count', 'duration_for_unique': 'max', 'duration_for_unique':'min'})
)

print(unique_week_calls)
unique_week_calls.sum() 
print()

                      duration_for_unique
week
2024-01-01/2024-01-07     0 days 00:00:16
2024-01-08/2024-01-14     0 days 00:00:13
2024-01-15/2024-01-21     0 days 00:00:13
2024-01-22/2024-01-28     0 days 00:00:13
2024-01-29/2024-02-04     0 days 00:00:13
2024-02-05/2024-02-11     0 days 00:00:14
2024-02-12/2024-02-18     0 days 00:00:12
2024-02-19/2024-02-25     0 days 00:00:11
2024-02-26/2024-03-03     0 days 00:00:12
2024-03-04/2024-03-10     0 days 00:00:12
2024-03-11/2024-03-17     0 days 00:00:12
2024-03-18/2024-03-24     0 days 00:00:11
2024-03-25/2024-03-31     0 days 00:00:12