In [1]:
import pandas as pd
import pickle
data = pd.read_pickle("cdr_clean.pkl")

In [2]:
data = data.drop(columns=['pkid'])

In [4]:
data.shape[0]

3805586

In [9]:
type(data.columns)

pandas.core.indexes.base.Index

In [17]:
counts = data.groupby(by=list(data.columns)).count()

In [20]:
counts.head()

Empty DataFrame
Columns: []
Index: [(1, 1, 20554141, 2024-01-16 10:11:47, 4369121193063, 393216, 20554142, +4321454093284, +4321454093284, 393216, 2024-01-16 10:11:52, 2024-01-16 10:11:52, +4321454093284, 0, HK010_CC, CSFC38K6092, 17, 17, 0, 0, 0, 0, 0, 0), (1, 1, 20554142, 2024-01-16 10:11:52, +4321454093284, 16, 20554096, +4369121193063, +4369121193063, 0, 2024-01-16 10:11:52, 2024-01-16 10:16:23, +4321454093284, 271, CSFC38K6092, BK053_000_Tele2, 12, 17, 0, 18, 0, 146, 18, 0), (1, 2, 20554145, 2024-01-16 10:11:49, 4368926414697, 393216, 20554148, +4368883460773, +436356240905, 393216, 2024-01-16 10:11:49, 2024-01-16 10:11:49, +4368883460773, 0, HK010_CC, Unity_Connection_Publisher, 17, 17, 5, 5, 15, 15, 5, 0), (1, 2, 20554148, 2024-01-16 10:11:49, +436356240905, 0, 39184270, +4368926414697, +4368926414697, 16, 2024-01-16 10:11:49, 2024-01-16 10:12:25, +4368883460773, 36, Unity_Connection_Publisher, BK044_000_Tele2, 17, 12, 0, 18, 0, 146, 18, 0), (1, 3, 20554152, 2024-01-16 10:11:49, +498883250014, 393216, 20554155, +433277014100, +4344124999, 393216, 2024-01-16 10:11:50, 2024-01-16 10:12:29, +433277014100, 39, BK016_000_Tele2, HK010_CC, 18, 18, 5, 5, 15, 15, 5, 0)]

In [23]:
data[data.duplicated()==True]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
3536363,1,363534,67747431,2024-02-20 13:05:01,0046133053414,0,67747687,+437134539429,+437134539429,27,...,BK044_000_Tele2,CSFC29KMCL,10,12,0,10,0,4,10,0