In [1]:
import pandas as pd

In [4]:
data = pd.read_pickle(r"C:\Users\lenka\Documents\data analýza\DA\PROJEKT\Hovory\zakl pandas\cdr_clean_NOb00.pkl")

In [5]:
# divala jsem se, jakych nabyva hodnot sloupec globalCallID_callManagerId
data['globalCallID_callManagerId'].value_counts()

globalCallID_callManagerId
1    1275456
2    1226745
4     524161
3     236474
0          2
Name: count, dtype: int64

Zobrazeni radku s callManagerId = 0: 
- neni hovor, takze nejspis vyradit

In [9]:
data[data['globalCallID_callManagerId'] == 0]

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
2978251,0,0,50409300,NaT,<NA>,41,50409301,<NA>,<NA>,0,...,10.1.52.233,<NA>,12,0,0,0,0,0,0,0
2978252,0,0,50409302,NaT,<NA>,41,50409303,<NA>,<NA>,0,...,10.5.3.233,<NA>,12,0,0,0,0,0,0,0

In [6]:
# otazka na duplicity pomoci duplicated
duplicates = data[data['pkid'].duplicated(keep=False)]
duplicates

Empty DataFrame
Columns: [globalCallID_callManagerId, globalCallID_callId, origLegCallIdentifier, dateTimeOrigination, callingPartyNumber, origCause_value, destLegIdentifier, originalCalledPartyNumber, finalCalledPartyNumber, destCause_value, dateTimeConnect, dateTimeDisconnect, lastRedirectDn, pkid, duration, origDeviceName, destDeviceName, origCallTerminationOnBehalfOf, destCallTerminationOnBehalfOf, origCalledPartyRedirectOnBehalfOf, lastRedirectRedirectOnBehalfOf, origCalledPartyRedirectReason, lastRedirectRedirectReason, joinOnBehalfOf, callSecuredStatus]
Index: []

[0 rows x 25 columns]

In [7]:
#otazka na duplicity pomoci podminky a value_counts
id_counts = data['pkid'].value_counts()
id_counts[id_counts > 1]

Series([], Name: count, dtype: Int64)

Pocet unikatnich hovoru v ramci mesice:

In [ ]:
# vytvoreni sloupce 'month'
# dt je přístup k datetime atributům
data['month'] = data['dateTimeOrigination'].dt.to_period('M')

unique_month_calls = (
    data.drop_duplicates(['globalCallID_callId', 'origLegCallIdentifier', 
                          'month']).groupby('month').size()
)

print(unique_month_calls)

month
2024-01    1095119
2024-02     994592
2024-03     957970
Freq: M, dtype: int64

In [11]:
data['week'] = data['dateTimeOrigination'].dt.to_period('W')

unique_week_calls = (
    data.drop_duplicates(['globalCallID_callId', 'origLegCallIdentifier', 
                          'week']).groupby('week').size()
)

print(unique_week_calls)

week
2024-01-01/2024-01-07    183748
2024-01-08/2024-01-14    264674
2024-01-15/2024-01-21    252641
2024-01-22/2024-01-28    241492
2024-01-29/2024-02-04    249582
2024-02-05/2024-02-11    238215
2024-02-12/2024-02-18    228351
2024-02-19/2024-02-25    235008
2024-02-26/2024-03-03    240145
2024-03-04/2024-03-10    236729
2024-03-11/2024-03-17    232167
2024-03-18/2024-03-24    232289
2024-03-25/2024-03-31    212640
Freq: W-SUN, dtype: int64