In [1]:
import pandas as pd
import pickle

In [2]:
data = pd.read_pickle(r"C:\Users\lenka\Documents\data analýza\DA\PROJEKT\Hovory\zakl pandas\cdr_clean_NOb00.pkl")

In [3]:
print("Pocet radku a sloupcu:", data.shape)
data.dtypes

Pocet radku a sloupcu: (3262838, 25)

globalCallID_callManagerId                    int64
globalCallID_callId                           int64
origLegCallIdentifier                         int64
dateTimeOrigination                  datetime64[ns]
callingPartyNumber                   string[python]
origCause_value                               int64
destLegIdentifier                             int64
originalCalledPartyNumber            string[python]
finalCalledPartyNumber               string[python]
destCause_value                               int64
dateTimeConnect                      datetime64[ns]
dateTimeDisconnect                   datetime64[ns]
lastRedirectDn                       string[python]
pkid                                 string[python]
duration                                      int64
origDeviceName                       string[python]
destDeviceName                       string[python]
origCallTerminationOnBehalfOf                 int64
destCallTerminationOnBehalfOf                 int64
origCalledPartyRedirectOnBehalfOf             int64
lastRedirectRedirectOnBehalfOf                int64
origCalledPartyRedirectReason                 int64
lastRedirectRedirectReason                    int64
joinOnBehalfOf                                int64
callSecuredStatus                             int64
dtype: object

In [4]:
print("\nPocet chybejicich NaN hodnot:")
data.isna().sum()

Pocet chybejicich NaN hodnot:

globalCallID_callManagerId                0
globalCallID_callId                       0
origLegCallIdentifier                     0
dateTimeOrigination                       2
callingPartyNumber                   550310
origCause_value                           0
destLegIdentifier                         0
originalCalledPartyNumber             60321
finalCalledPartyNumber                48072
destCause_value                           0
dateTimeConnect                      552543
dateTimeDisconnect                        0
lastRedirectDn                        60352
pkid                                      0
duration                                  0
origDeviceName                       549251
destDeviceName                       160125
origCallTerminationOnBehalfOf             0
destCallTerminationOnBehalfOf             0
origCalledPartyRedirectOnBehalfOf         0
lastRedirectRedirectOnBehalfOf            0
origCalledPartyRedirectReason             0
lastRedirectRedirectReason                0
joinOnBehalfOf                            0
callSecuredStatus                         0
dtype: int64

In [6]:
print("Statistické shrnutí sloupce 'duration':")
data["duration"].describe().round(0)

Statistické shrnutí sloupce 'duration':

count    3262838.0
mean          76.0
std          249.0
min            0.0
25%            0.0
50%            7.0
75%           65.0
max        43200.0
Name: duration, dtype: float64

In [7]:

display(data.head())

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [8]:
data[["dateTimeOrigination", "dateTimeConnect", "dateTimeDisconnect"]].head()

  dateTimeOrigination     dateTimeConnect  dateTimeDisconnect
0 2024-01-01 01:20:13 2024-01-01 01:20:14 2024-01-01 01:20:22
1 2024-01-01 03:08:00 2024-01-01 03:08:02 2024-01-01 03:08:14
2 2024-01-01 05:07:47                 NaT 2024-01-01 05:07:47
3 2024-01-01 05:41:29 2024-01-01 05:41:31 2024-01-01 05:42:05
4 2024-01-01 06:07:14 2024-01-01 06:07:15 2024-01-01 06:07:50

In [14]:
unique_calls = (
    data.groupby(["globalCallID_callId", "origLegCallIdentifier"])
    .ngroups
)
print(f"skutecny pocet unikatnich hovoru: {unique_calls}")

skutecny pocet unikatnich hovoru: 3047683

In [15]:
print("celkovy pocet radku:", len(data))
print("Skutecny pocet hovoru:", unique_calls)
print("Pocet duplicitnich zaznamu:", len(data) - unique_calls)

celkovy pocet radku: 3262838
Skutecny pocet hovoru: 3047683
Pocet duplicitnich zaznamu: 215155