In [74]:
import pandas as pd

In [61]:
data = pd.read_pickle('CDR_soubor.pkl')

In [62]:
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]

poreseni hlavicky

In [63]:
list(data.columns[:10])

['cdrRecordType',
 'globalCallID_callManagerId',
 'globalCallID_callId',
 'origLegCallIdentifier',
 'dateTimeOrigination',
 'origNodeId',
 'origSpan',
 'origIpAddr',
 'callingPartyNumber',
 'callingPartyUnicodeLoginUserID']

In [64]:
chosen_data = data[[
    'globalCallID_callManagerId', 'globalCallID_callId',
    'origLegCallIdentifier', 'dateTimeOrigination',
    'callingPartyNumber', 'origCause_value', 'destLegIdentifier',
    'originalCalledPartyNumber', 'finalCalledPartyNumber',
    'destCause_value', 'dateTimeConnect', 'dateTimeDisconnect',
    'lastRedirectDn', 'pkid', 'duration', 'origDeviceName',
    'destDeviceName', 'origCallTerminationOnBehalfOf',
    'destCallTerminationOnBehalfOf', 'origCalledPartyRedirectOnBehalfOf',
    'lastRedirectRedirectOnBehalfOf', 'origCalledPartyRedirectReason',
    'lastRedirectRedirectReason', 'joinOnBehalfOf', 'callSecuredStatus'
]]

In [65]:
chosen_data = chosen_data.reset_index(drop=True)

In [ ]:
poreseni spatneho indexovani

In [66]:
chosen_data.head(5)

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,1704072013,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,1704078480,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,1704085667,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,1704087689,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,1704089234,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [67]:
chosen_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3805586 entries, 0 to 3805585
Data columns (total 25 columns):
 #   Column                             Dtype
---  ------                             -----
 0   globalCallID_callManagerId         int64
 1   globalCallID_callId                int64
 2   origLegCallIdentifier              int64
 3   dateTimeOrigination                int64
 4   callingPartyNumber                 object
 5   origCause_value                    int64
 6   destLegIdentifier                  int64
 7   originalCalledPartyNumber          object
 8   finalCalledPartyNumber             object
 9   destCause_value                    int64
 10  dateTimeConnect                    int64
 11  dateTimeDisconnect                 int64
 12  lastRedirectDn                     object
 13  pkid                               object
 14  duration                           int64
 15  origDeviceName                     object
 16  destDeviceName                     object
 17  origCallTerminationOnBehalfOf      int64
 18  destCallTerminationOnBehalfOf      int64
 19  origCalledPartyRedirectOnBehalfOf  int64
 20  lastRedirectRedirectOnBehalfOf     int64
 21  origCalledPartyRedirectReason      int64
 22  lastRedirectRedirectReason         int64
 23  joinOnBehalfOf                     int64
 24  callSecuredStatus                  int64
dtypes: int64(18), object(7)
memory usage: 725.9+ MB

In [68]:
chosen_data.to_pickle('cdr_files_chosen_columns.pkl')

In [69]:
data = pd.read_pickle('CMR_soubor.pkl')

In [75]:
data.columns = [col[0] if isinstance(col, tuple) else col for col in data.columns]

In [76]:
chosen_data = data[['globalCallID_callManagerId', 'globalCallID_callId',
                    'nodeId', 'directoryNum', 'callIdentifier', 
                    'dateTimeStamp', 'numberPacketsSent', 'numberOctetsSent',
                    'numberPacketsReceived', 'numberOctetsReceived',
                    'numberPacketsLost', 'jitter', 'latency', 'pkid', 
                    'varVQMetrics', 'duration', 'videoContentType',
                    'videoContentType_channel2']]

In [77]:
chosen_data = chosen_data.reset_index(drop=True)

In [78]:
chosen_data.head(5)

,globalCallID_callManagerId,globalCallID_callId,nodeId,directoryNum,callIdentifier,dateTimeStamp,numberPacketsSent,numberOctetsSent,numberPacketsReceived,numberOctetsReceived,numberPacketsLost,jitter,latency,pkid,varVQMetrics,duration,videoContentType,videoContentType_channel2
0,1,16615192,1,NaN,19957589,1704095862,700,112000,711,113760,0,0,0,0fa8a04b-e721-4f36-98a5-eb9a628a337b,NaN,14.0,NaN,NaN
1,1,16615193,1,43429526179121,19957592,1704096589,0,0,0,0,0,1,0,94416b54-fef7-4aeb-a80a-00fd935f62d0,NaN,NaN,NaN,NaN
2,1,16615194,1,43429526179121,19957594,1704096596,0,0,0,0,0,1,0,1e2174ae-7610-4f49-a9e2-0ca8707e2c4d,NaN,NaN,NaN,NaN
3,1,16615195,1,43429526179121,19957596,1704096598,0,0,0,0,0,1,0,9fecaba6-292f-49cc-8e1d-28d6913a920d,NaN,NaN,NaN,NaN
4,1,16615196,1,NaN,19957598,1704096945,588,94080,594,94563,0,0,0,fea9bc46-a321-42ad-b368-5eb51237031e,NaN,11.0,NaN,NaN

In [79]:
chosen_data.to_pickle('cmr_files_chosen_columns.pkl')