In [35]:
import pandas as pd

data = pd.read_pickle(
    "cdr_files_chosen_columns.pkl"  
)

In [36]:
data.head(10)

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,1704072013,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,1704078480,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,1704085667,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,1704087689,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,1704089234,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0
5,1,16615187,19957572,1704092714,436062952952,16,19957575,43751547410,43139117000,0,...,BK004_000_Tele2,HK010_CC,12,0,5,5,15,15,5,0
6,1,16615188,19957576,1704093826,435224294268,16,19957577,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
7,1,16615189,19957578,1704095062,4342669920759,16,19957579,433738509500150,433738509500150,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
8,1,16615190,19957580,1704095296,436062952952,16,19957583,43751547410,43139117000,0,...,BK004_000_Tele2,HK010_CC,12,0,5,5,15,15,5,0
9,1,16615191,19957584,1704095409,4329317479456,16,19957588,43460548172,43351974100,0,...,BK001_000_Tele2,HK010_CC,12,0,5,5,178,178,5,0

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3805586 entries, 0 to 3805585
Data columns (total 25 columns):
 #   Column                             Dtype
---  ------                             -----
 0   globalCallID_callManagerId         int64
 1   globalCallID_callId                int64
 2   origLegCallIdentifier              int64
 3   dateTimeOrigination                int64
 4   callingPartyNumber                 object
 5   origCause_value                    int64
 6   destLegIdentifier                  int64
 7   originalCalledPartyNumber          object
 8   finalCalledPartyNumber             object
 9   destCause_value                    int64
 10  dateTimeConnect                    int64
 11  dateTimeDisconnect                 int64
 12  lastRedirectDn                     object
 13  pkid                               object
 14  duration                           int64
 15  origDeviceName                     object
 16  destDeviceName                     object
 17  origCallTerminationOnBehalfOf      int64
 18  destCallTerminationOnBehalfOf      int64
 19  origCalledPartyRedirectOnBehalfOf  int64
 20  lastRedirectRedirectOnBehalfOf     int64
 21  origCalledPartyRedirectReason      int64
 22  lastRedirectRedirectReason         int64
 23  joinOnBehalfOf                     int64
 24  callSecuredStatus                  int64
dtypes: int64(18), object(7)
memory usage: 725.9+ MB

In [38]:
len(data.columns)

25

In [39]:
data = data.astype({col: "string" for col in data.select_dtypes(include="object").columns})

In [40]:
casove_sloupce=["dateTimeOrigination", "dateTimeConnect", "dateTimeDisconnect"]
for sloupec in casove_sloupce:
    data[sloupec] = pd.to_datetime(data[sloupec], unit='s')

In [41]:
for sloupec in casove_sloupce:
        data[sloupec]=data[sloupec].replace(pd.Timestamp('1970-01-01 00:00:00'), pd.NaT)
data[casove_sloupce]

        dateTimeOrigination     dateTimeConnect  dateTimeDisconnect
0       2024-01-01 01:20:13 2024-01-01 01:20:14 2024-01-01 01:20:22
1       2024-01-01 03:08:00 2024-01-01 03:08:02 2024-01-01 03:08:14
2       2024-01-01 05:07:47                 NaT 2024-01-01 05:07:47
3       2024-01-01 05:41:29 2024-01-01 05:41:31 2024-01-01 05:42:05
4       2024-01-01 06:07:14 2024-01-01 06:07:15 2024-01-01 06:07:50
...                     ...                 ...                 ...
3805581 2024-03-29 19:15:54 2024-03-29 19:15:54 2024-03-29 19:16:39
3805582 2024-03-30 15:12:29 2024-03-30 15:12:42 2024-03-30 15:29:03
3805583 2024-03-30 15:34:07 2024-03-30 15:34:31 2024-03-30 16:06:17
3805584 2024-03-30 18:13:14 2024-03-30 18:13:31 2024-03-30 18:14:02
3805585 2024-03-31 10:04:59                 NaT 2024-03-31 10:05:15

[3805586 rows x 3 columns]

In [42]:
data.head(5)

,globalCallID_callManagerId,globalCallID_callId,origLegCallIdentifier,dateTimeOrigination,callingPartyNumber,origCause_value,destLegIdentifier,originalCalledPartyNumber,finalCalledPartyNumber,destCause_value,...,origDeviceName,destDeviceName,origCallTerminationOnBehalfOf,destCallTerminationOnBehalfOf,origCalledPartyRedirectOnBehalfOf,lastRedirectRedirectOnBehalfOf,origCalledPartyRedirectReason,lastRedirectRedirectReason,joinOnBehalfOf,callSecuredStatus
0,1,16615182,19957562,2024-01-01 01:20:13,437734693017,16,19957563,4344124999,4344124999,0,...,BK016_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
1,1,16615183,19957564,2024-01-01 03:08:00,436618449646,16,19957565,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
2,1,16615184,19957566,2024-01-01 05:07:47,436359992566,16,19957567,433738509500050,433738509500050,0,...,BK044_023_Tele2,HK010_CC,12,0,0,0,0,0,0,0
3,1,16615185,19957568,2024-01-01 05:41:29,9999,16,19957569,4314014190122,4314014190122,0,...,BK053_000_Tele2,HK010_CC,12,0,0,0,0,0,0,0
4,1,16615186,19957570,2024-01-01 06:07:14,433496903750,0,19957571,4373935601800,4373935601800,16,...,BK075_000_Tele2,HK010_CC,0,12,0,0,0,0,0,0

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3805586 entries, 0 to 3805585
Data columns (total 25 columns):
 #   Column                             Dtype
---  ------                             -----
 0   globalCallID_callManagerId         int64
 1   globalCallID_callId                int64
 2   origLegCallIdentifier              int64
 3   dateTimeOrigination                datetime64[ns]
 4   callingPartyNumber                 string
 5   origCause_value                    int64
 6   destLegIdentifier                  int64
 7   originalCalledPartyNumber          string
 8   finalCalledPartyNumber             string
 9   destCause_value                    int64
 10  dateTimeConnect                    datetime64[ns]
 11  dateTimeDisconnect                 datetime64[ns]
 12  lastRedirectDn                     string
 13  pkid                               string
 14  duration                           int64
 15  origDeviceName                     string
 16  destDeviceName                     string
 17  origCallTerminationOnBehalfOf      int64
 18  destCallTerminationOnBehalfOf      int64
 19  origCalledPartyRedirectOnBehalfOf  int64
 20  lastRedirectRedirectOnBehalfOf     int64
 21  origCalledPartyRedirectReason      int64
 22  lastRedirectRedirectReason         int64
 23  joinOnBehalfOf                     int64
 24  callSecuredStatus                  int64
dtypes: datetime64[ns](3), int64(15), string(7)
memory usage: 725.9 MB

nutne prevest do pickel, kvupi datatypum!

In [44]:
data.to_pickle("cdr_clean.pkl")